### ISSUE TITLE
New (News) blog post is not appearing on website

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda.org#40]
See https://github.com/quanteda/quanteda.org/pulls?q=is%3Apr+is%3Aclosed for background.

The post https://github.com/quanteda/quanteda.org/blob/master/content/news/joss-paper.md is not appearing on the News feed, despite being in `master`.

@ciflikli @koheiw any ideas?

**Comment by stefan-mueller** [comment]
Thanks @koheiw. So I assume we always need to explicitly build the website with `blogdown::build_site()`in RStudio when we add a news article. Good to know.

**Comment by koheiw** [comment]
Yes, you should run `blogdown::build_site()` or `blogdown::serve_site()`. The former command rebuilds whole website, while the latter does only pages that need to be updated. For a blog post, the latter command should be enough. (I never asked you to do this for the tutorials site, because I though you don't have necessary files on your machine).

**Comment by kbenoit** [comment]
I think 

<img width="424" alt="screenshot 2018-10-09 15 44 52" src="https://user-images.githubusercontent.com/2182246/46694322-702b6000-cbda-11e8-9fb4-02bb710eb1a6.png">

works too.
